name: flutter_conditonal_example
description: "An example project for flutter_conditional"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_conditional: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true