name: flutter_conditional
description: 'A Flutter package for rendering widgets conditionally.'
publish_to: 'none'
version: 1.0.0

homepage: https://github.com/scialapp/flutter_conditional

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0